include themes/everforest-hard.conf

font_family family="Agave Nerd Font Mono" style="Regular"
bold_font family="Agave Nerd Font Mono" style="Regular"
font_size 12.5
disable_ligatures never
shell_integration no-cursor
cursor_shape beam
cursor_blink_interval 1
window_padding_width 5
progress_bar hidden
