include themes/koda.conf

font_family family="FantasqueSansM Nerd Font" style="Regular"
bold_font family="FantasqueSansM Nerd Font" style="Regular"
font_size 13
disable_ligatures never
shell_integration no-cursor
cursor_shape underline
cursor_blink_interval 1
window_padding_width 5
