# COLORS
# ----------
# EVERFOREST: https://github.com/neanias/everforest-nvim
# bg: rgb(30, 35, 38)
# text: rgb(211, 198, 170)
# ----------
# KODA: https://github.com/oskarnurm/koda.nvim
# bg: rgb(16, 16, 16)
# text: rgb(176, 176, 176)
# ----------
# VAGUE: https://github.com/vague-theme/vague.nvim
# bg: rgb(20, 20, 21)
# text: rgb(205, 205, 205)

general {
  hide_cursor        = true
  ignore_empty_input = true
  immediate_render   = true
  fail_timeout       = 200
}

animations {
  enabled = false
}

background {
  monitor =
  color   = rgb(20, 20, 21)
}

input-field {
  monitor           =
  size              = 20%, 5%
  outline_thickness = 0
  inner_color       = rgba(0, 0, 0, 0)
  outer_color       = rgba(0, 0, 0, 0)
  check_color       = rgba(0, 0, 0, 0)
  dots_text_format  = <b>*</b>
  dots_size         = 0.2
  dots_spacing      = 0.4
  font_family       = Iosevka Nerd Font Bold
  placeholder_text  =
  font_color        = rgb(205, 205, 205)
  fade_on_empty     = false
  rounding          = 0
  position          = 0, -40
}

label {
  monitor     =
  text        = $TIME12
  text_align  = center
  color       = rgb(205, 205, 205)
  font_size   = 20
  font_family = Iosevka Nerd Font Bold
}

