# COLORS
# ----------
# EVERFOREST
# bg: rgb(30, 35, 38)
# text: rgb(211, 198, 170)
# ---------
# KODA:
# bg: rgb(16, 16, 16)
# text: rgb(176, 176, 176)

general {
  hide_cursor        = true
  ignore_empty_input = true
  immediate_render   = true
  fail_timeout       = 200
}

animations {
  enabled = false
}

background {
  monitor =
  color   = rgb(30, 35, 38)
}

input-field {
  monitor           =
  size              = 20%, 5%
  outline_thickness = 0
  inner_color       = rgba(0, 0, 0, 0)
  outer_color       = rgba(0, 0, 0, 0)
  check_color       = rgba(0, 0, 0, 0)
  dots_text_format  = <b>*</b>
  dots_size         = 0.2
  dots_spacing      = 0.4
  font_family       = Agave Nerd Font Bold
  placeholder_text  =
  font_color        = rgb(211, 198, 170)
  fade_on_empty     = false
  rounding          = 0
  position          = 0, -40
}

label {
  monitor     =
  text        = $TIME12
  text_align  = center
  color       = rgb(211, 198, 170)
  font_size   = 25
  font_family = Agave Nerd Font Bold
}

