foreground                      #cdcdcd
background                      #141415

cursor                          #cdcdcd

url_color                       #aeaed1

#: black
color0                          #141415
color8                          #1c1c24

#: red
color1                          #c48282
color9                          #c48282

#: green
color2                          #b4d4cf
color10                         #b4d4cf

#: yellow
color3                          #e8b589
color11                         #e8b589

#: blue
color4                          #6e94b2
color12                         #6e94b2

#: magenta
color5                          #bb9dbd
color13                         #bb9dbd

#: cyan
color6                          #aeaed1
color14                         #aeaed1

#: white
color7                          #cdcdcd
color15                         #cdcdcd
